# -*- coding: utf-8 -*-
"""YOLO_DEMO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zkCsEkK1VBhhQMgLiwRCCtsH8mG_spQf
"""

!pip install ultralytics

from ultralytics import YOLO
from matplotlib import pyplot as plt
from PIL import Image

#Detection model
det_model=YOLO('yolov8n.pt')
#Instance segmentation model
inst_model=YOLO('yolov8n-seg.pt')
#the yolo model version 8 is used here which is much better than previous models in
#various aspects such as better recall metrics results much faster then previous as
#it is a single look instance model having accuracy lesser as compared to faster R-CNN
#or double look instance model which take greater time but gives better acuracy
#hence a descison is to be made in between accordingly for constant detecion in real-life
#YOLO is quite favourable and widely used

from google.colab import drive
drive.mount('/content/drive')

img = '/content/drive/MyDrive/img_data/4k-kitchen-background-3840-x-2160-s6yemlhfd3r4suor.jpg'
detection_results=det_model.predict(img)
instance_results=inst_model.predict(img)

demo_img='/content/drive/MyDrive/img_data/WhatsApp Image 2023-11-22 at 9.01.52 PM.jpeg'
demo_detection_res=det_model.predict(demo_img);
instance_detection_res=inst_model.predict(demo_img);

det_res_arr=demo_detection_res[0].plot()
inst_res_arr=instance_detection_res[0].plot()
fig=plt.figure(figsize=(18,9))
ax1=fig.add_subplot(1,2,1)
ax1.set_title("Object Detection")
ax1.imshow(det_res_arr)
ax2=fig.add_subplot(1,2,2)
ax2.set_title("Instance Segmentation")
ax2.imshow(inst_res_arr)

detection_result_arr=detection_results[0].plot()
instance_result_array=instance_results[0].plot()
fig=plt.figure(figsize=(18,9))
ax1=fig.add_subplot(1,2,1)
ax1.set_title("Object Detection")
ax1.imshow(detection_result_arr)
ax2=fig.add_subplot(1,2,2)
ax2.set_title("Instance Segmentation")
ax2.imshow(instance_result_array)

result=instance_results[0]
len(result.boxes)